// Code generated by protoc-gen-pico. DO NOT EDIT.
// source: proto2.proto
//
// versions:
//     protoc-gen-pico: v0.0.5-0.20260818151457-457df939b0d3
//     protoc:          v7.35.1

package pico2

import (
	picobuf "storj.io/picobuf"
	strconv "strconv"
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_READY       State = 1
)

func (m State) String() string {
	switch m {
	case State_STATE_UNSPECIFIED:
		return "STATE_UNSPECIFIED"
	case State_STATE_READY:
		return "STATE_READY"
	default:
		return "State(" + strconv.Itoa(int(m)) + ")"
	}
}

type Message struct {
	Number *int32  `json:"number,omitzero"`
	Text   *string `json:"text,omitzero"`
	Data   *[]byte `json:"data,omitzero"`
	State  *State  `json:"state,omitzero"`
}

func (m *Message) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	if m.Number != nil {
		c.AlwaysInt32(1, m.Number)
	}
	c.WithoutUTF8Validation(func() {
		if m.Text != nil {
			c.AlwaysString(2, m.Text)
		}
	})
	if m.Data != nil {
		c.AlwaysBytes(3, m.Data)
	}
	if m.State != nil {
		c.AlwaysInt32(4, (*int32)(m.State))
	}
	return true
}

func (m *Message) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	if c.PendingField() == 1 {
		m.Number = new(int32)
		c.Int32(1, m.Number)
	}
	c.WithoutUTF8Validation(func() {
		if c.PendingField() == 2 {
			m.Text = new(string)
			c.String(2, m.Text)
		}
	})
	if c.PendingField() == 3 {
		m.Data = new([]byte)
		c.Bytes(3, m.Data)
	}
	if c.PendingField() == 4 {
		m.State = new(State)
		c.Int32(4, (*int32)(m.State))
	}
}
