// Code generated by protoc-gen-pico. DO NOT EDIT.
// source: editions.proto
//
// versions:
//     protoc-gen-pico: v0.0.5-0.20260818151457-457df939b0d3
//     protoc:          v7.35.1

package editionpico

import (
	picobuf "storj.io/picobuf"
	strconv "strconv"
)

type ClosedState int32

const (
	ClosedState_CLOSED_STATE_UNSPECIFIED ClosedState = 0
	ClosedState_CLOSED_STATE_READY       ClosedState = 1
)

func (m ClosedState) String() string {
	switch m {
	case ClosedState_CLOSED_STATE_UNSPECIFIED:
		return "CLOSED_STATE_UNSPECIFIED"
	case ClosedState_CLOSED_STATE_READY:
		return "CLOSED_STATE_READY"
	default:
		return "ClosedState(" + strconv.Itoa(int(m)) + ")"
	}
}

type Message struct {
	ExplicitNumber  *int32        `json:"explicit_number,omitzero"`
	ExplicitText    *string       `json:"explicit_text,omitzero"`
	ExplicitData    *[]byte       `json:"explicit_data,omitzero"`
	ImplicitNumber  int32         `json:"implicit_number,omitzero"`
	ImplicitText    string        `json:"implicit_text,omitzero"`
	ImplicitData    []byte        `json:"implicit_data,omitzero"`
	PackedNumbers   []int32       `json:"packed_numbers,omitzero"`
	ExpandedNumbers []int32       `json:"expanded_numbers,omitzero"`
	Nested          *Nested       `json:"nested,omitzero"`
	ClosedState     *ClosedState  `json:"closed_state,omitzero"`
	ClosedStates    []ClosedState `json:"closed_states,omitzero"`
	// Types that are assignable to ClosedSelection:
	//
	//	*Message_SelectedClosedState
	ClosedSelection isMessage_ClosedSelection
}

func (m *Message) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	if m.ExplicitNumber != nil {
		c.AlwaysInt32(1, m.ExplicitNumber)
	}
	if m.ExplicitText != nil {
		c.AlwaysString(2, m.ExplicitText)
	}
	if m.ExplicitData != nil {
		c.AlwaysBytes(3, m.ExplicitData)
	}
	c.Int32(4, &m.ImplicitNumber)
	c.String(5, &m.ImplicitText)
	c.Bytes(6, &m.ImplicitData)
	c.RepeatedInt32(7, &m.PackedNumbers)
	for i := range m.ExpandedNumbers {
		c.AlwaysInt32(8, &m.ExpandedNumbers[i])
	}
	c.Group(9, m.Nested.Encode)
	if m.ClosedState != nil {
		c.AlwaysInt32(10, (*int32)(m.ClosedState))
	}
	c.RepeatedEnum(11, len(m.ClosedStates), func(index uint) int32 {
		if index < uint(len(m.ClosedStates)) {
			return (int32)(m.ClosedStates[index])
		}
		return 0
	})
	if m, ok := m.ClosedSelection.(*Message_SelectedClosedState); ok {
		c.AlwaysInt32(12, (*int32)(&m.SelectedClosedState))
	}
	return true
}

func (m *Message) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	if c.PendingField() == 1 {
		m.ExplicitNumber = new(int32)
		c.Int32(1, m.ExplicitNumber)
	}
	if c.PendingField() == 2 {
		m.ExplicitText = new(string)
		c.String(2, m.ExplicitText)
	}
	if c.PendingField() == 3 {
		m.ExplicitData = new([]byte)
		c.Bytes(3, m.ExplicitData)
	}
	c.Int32(4, &m.ImplicitNumber)
	c.String(5, &m.ImplicitText)
	c.Bytes(6, &m.ImplicitData)
	c.RepeatedInt32(7, &m.PackedNumbers)
	c.RepeatedInt32(8, &m.ExpandedNumbers)
	c.Group(9, func(c *picobuf.Decoder) {
		if m.Nested == nil {
			m.Nested = new(Nested)
		}
		m.Nested.Decode(c)
	})
	if c.PendingField() == 10 {
		m.ClosedState = new(ClosedState)
		c.Int32(10, (*int32)(m.ClosedState))
	}
	c.RepeatedEnum(11, func(x int32) {
		m.ClosedStates = append(m.ClosedStates, (ClosedState)(x))
	})
	if c.PendingField() == 12 {
		var x *Message_SelectedClosedState
		if z, ok := m.ClosedSelection.(*Message_SelectedClosedState); ok {
			x = z
		} else {
			x = new(Message_SelectedClosedState)
			m.ClosedSelection = x
		}
		m := x
		c.Int32(12, (*int32)(&m.SelectedClosedState))
	}
}

type isMessage_ClosedSelection interface{ isMessage_ClosedSelection() }

type Message_SelectedClosedState struct {
	SelectedClosedState ClosedState
}

func (*Message_SelectedClosedState) isMessage_ClosedSelection() {}

type Nested struct {
	Value *int32 `json:"value,omitzero"`
}

func (m *Nested) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	if m.Value != nil {
		c.AlwaysInt32(1, m.Value)
	}
	return true
}

func (m *Nested) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	if c.PendingField() == 1 {
		m.Value = new(int32)
		c.Int32(1, m.Value)
	}
}

type RequiredMessage struct {
	RequiredNumber *int32 `json:"required_number,omitzero"`
}

func (m *RequiredMessage) PicoValidateRequired() error {
	if m == nil {
		return nil
	}
	if m.RequiredNumber == nil {
		return picobuf.MissingRequiredField(1)
	}
	return nil
}

func (m *RequiredMessage) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	if m.RequiredNumber != nil {
		c.AlwaysInt32(1, m.RequiredNumber)
	}
	return true
}

func (m *RequiredMessage) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	if c.PendingField() == 1 {
		m.RequiredNumber = new(int32)
		c.Int32(1, m.RequiredNumber)
	}
}

type RequiredParent struct {
	Child *RequiredMessage `json:"child,omitzero"`
}

func (m *RequiredParent) PicoValidateRequired() error {
	if m == nil {
		return nil
	}
	if err := picobuf.ValidateRequired(m.Child); err != nil {
		return err
	}
	return nil
}

func (m *RequiredParent) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.Message(1, m.Child.Encode)
	return true
}

func (m *RequiredParent) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.Message(1, func(c *picobuf.Decoder) {
		if m.Child == nil {
			m.Child = new(RequiredMessage)
		}
		m.Child.Decode(c)
	})
}
