// Code generated by protoc-gen-pico. DO NOT EDIT.
// source: editions.proto
//
// versions:
//     protoc-gen-pico: v0.0.5-0.20260818151457-457df939b0d3
//     protoc:          v7.35.1

package editionpico

import (
	picobuf "storj.io/picobuf"
)

type Message struct {
	ExplicitNumber *int32  `json:"explicit_number,omitzero"`
	ExplicitText   *string `json:"explicit_text,omitzero"`
	ExplicitData   *[]byte `json:"explicit_data,omitzero"`
	ImplicitNumber int32   `json:"implicit_number,omitzero"`
	ImplicitText   string  `json:"implicit_text,omitzero"`
	ImplicitData   []byte  `json:"implicit_data,omitzero"`
}

func (m *Message) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	if m.ExplicitNumber != nil {
		c.AlwaysInt32(1, m.ExplicitNumber)
	}
	if m.ExplicitText != nil {
		c.AlwaysString(2, m.ExplicitText)
	}
	if m.ExplicitData != nil {
		c.AlwaysBytes(3, m.ExplicitData)
	}
	c.Int32(4, &m.ImplicitNumber)
	c.String(5, &m.ImplicitText)
	c.Bytes(6, &m.ImplicitData)
	return true
}

func (m *Message) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	if c.PendingField() == 1 {
		m.ExplicitNumber = new(int32)
		c.Int32(1, m.ExplicitNumber)
	}
	if c.PendingField() == 2 {
		m.ExplicitText = new(string)
		c.String(2, m.ExplicitText)
	}
	if c.PendingField() == 3 {
		m.ExplicitData = new([]byte)
		c.Bytes(3, m.ExplicitData)
	}
	c.Int32(4, &m.ImplicitNumber)
	c.String(5, &m.ImplicitText)
	c.Bytes(6, &m.ImplicitData)
}
