// Code generated by protoc-gen-pico. DO NOT EDIT.
// source: types.proto
//
// versions:
//     protoc-gen-pico: (devel)
//     protoc:          v3.17.3

package protocompat

import (
	picobuf "storj.io/picobuf"
)

type LanguagePico int32

const (
	Language_UNKNOWNPico LanguagePico = 0
	Language_ENGLISHPico LanguagePico = 1
	Language_SPANISHPico LanguagePico = 3
	Language_FRENCHPico  LanguagePico = 4
	Language_GERMANPico  LanguagePico = 5
)

type TypesPico struct {
	Int32           int32
	Int64           int64
	Uint32          uint32
	Uint64          uint64
	Sint32          int32
	Sint64          int64
	Fixed32         uint32
	Fixed64         uint64
	Sfixed32        int32
	Sfixed64        int64
	Float           float32
	Double          float64
	Bool            bool
	String_         string
	Bytes           []byte
	Message         MessagePico
	OptionalMessage *OptionalMessagePico
}

func (m *TypesPico) Picobuf(c *picobuf.Codec) bool {
	if m == nil {
		return false
	}
	c.Int32(1, &m.Int32)
	c.Int64(2, &m.Int64)
	c.Uint32(3, &m.Uint32)
	c.Uint64(4, &m.Uint64)
	c.Sint32(5, &m.Sint32)
	c.Sint64(6, &m.Sint64)
	c.Fixed32(7, &m.Fixed32)
	c.Fixed64(8, &m.Fixed64)
	c.Sfixed32(9, &m.Sfixed32)
	c.Sfixed64(10, &m.Sfixed64)
	c.Float(11, &m.Float)
	c.Double(12, &m.Double)
	c.Bool(13, &m.Bool)
	c.String(14, &m.String_)
	c.Bytes(15, &m.Bytes)
	c.PresentMessage(16, m.Message.Picobuf)
	c.Message(17, func(c *picobuf.Codec) bool {
		if c.IsDecoding() && m.OptionalMessage == nil {
			m.OptionalMessage = new(OptionalMessagePico)
		}
		return m.OptionalMessage.Picobuf(c)
	})
	return true
}

type RepeatedTypesPico struct {
	Int32    []int32
	Int64    []int64
	Uint32   []uint32
	Uint64   []uint64
	Sint32   []int32
	Sint64   []int64
	Fixed32  []uint32
	Fixed64  []uint64
	Sfixed32 []int32
	Sfixed64 []int64
	Float    []float32
	Double   []float64
	Bool     []bool
	String_  []string
	Bytes    [][]byte
	Message  []*MessagePico
}

func (m *RepeatedTypesPico) Picobuf(c *picobuf.Codec) bool {
	if m == nil {
		return false
	}
	c.RepeatedInt32(1, &m.Int32)
	c.RepeatedInt64(2, &m.Int64)
	c.RepeatedUint32(3, &m.Uint32)
	c.RepeatedUint64(4, &m.Uint64)
	c.RepeatedSint32(5, &m.Sint32)
	c.RepeatedSint64(6, &m.Sint64)
	c.RepeatedFixed32(7, &m.Fixed32)
	c.RepeatedFixed64(8, &m.Fixed64)
	c.RepeatedSfixed32(9, &m.Sfixed32)
	c.RepeatedSfixed64(10, &m.Sfixed64)
	c.RepeatedFloat(11, &m.Float)
	c.RepeatedDouble(12, &m.Double)
	c.RepeatedBool(13, &m.Bool)
	c.RepeatedString(14, &m.String_)
	c.RepeatedBytes(15, &m.Bytes)
	c.RepeatedMessage(16, func(c *picobuf.Codec, index int) bool {
		if c.IsDecoding() && index == -1 {
			m.Message = append(m.Message, new(MessagePico))
		}
		if index >= len(m.Message) {
			return false
		}
		if index < 0 {
			index = len(m.Message) - 1
		}
		x := m.Message[index]
		x.Picobuf(c)
		return true
	})
	return true
}

type RepeatedMixedPico struct {
	Int32   int32
	Message []*MessagePico
}

func (m *RepeatedMixedPico) Picobuf(c *picobuf.Codec) bool {
	if m == nil {
		return false
	}
	c.Int32(1, &m.Int32)
	c.RepeatedMessage(16, func(c *picobuf.Codec, index int) bool {
		if c.IsDecoding() && index == -1 {
			m.Message = append(m.Message, new(MessagePico))
		}
		if index >= len(m.Message) {
			return false
		}
		if index < 0 {
			index = len(m.Message) - 1
		}
		x := m.Message[index]
		x.Picobuf(c)
		return true
	})
	return true
}

type MessagePico struct {
	Int32 int32
	Int64 int64
}

func (m *MessagePico) Picobuf(c *picobuf.Codec) bool {
	if m == nil {
		return false
	}
	c.Int32(1, &m.Int32)
	c.Int64(2, &m.Int64)
	return true
}

type PersonPico struct {
	Name     string
	Birthday int64
	Phone    string
	Siblings int32
	Spouse   bool
	Money    float64
	Primary  LanguagePico
	Spoken   []LanguagePico
}

func (m *PersonPico) Picobuf(c *picobuf.Codec) bool {
	if m == nil {
		return false
	}
	c.String(1, &m.Name)
	c.Int64(2, &m.Birthday)
	c.String(3, &m.Phone)
	c.Int32(4, &m.Siblings)
	c.Bool(5, &m.Spouse)
	c.Double(6, &m.Money)
	c.Int32(7, (*int32)(&m.Primary))
	c.RepeatedEnum(8, func(index int) (*int32, bool) {
		if c.IsDecoding() && index == -1 {
			m.Spoken = append(m.Spoken, 0)
		}
		if index >= len(m.Spoken) {
			return nil, false
		}
		if index < 0 {
			index = len(m.Spoken) - 1
		}
		return (*int32)(&m.Spoken[index]), true
	})
	return true
}

type MapPico struct {
	Values map[string]string
}

func (m *MapPico) Picobuf(c *picobuf.Codec) bool {
	if m == nil {
		return false
	}
	c.MapStringString(1, &m.Values)
	return true
}

type OptionalMessagePico struct {
	Int32 int32
}

func (m *OptionalMessagePico) Picobuf(c *picobuf.Codec) bool {
	if m == nil {
		return false
	}
	c.Int32(1, &m.Int32)
	return true
}
