// Copyright (C) 2021 Storj Labs, Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: pico.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageOptions struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AlwaysPresent             bool                   `protobuf:"varint,1,opt,name=always_present,json=alwaysPresent,proto3" json:"always_present,omitempty"`
	CaptureUnrecognizedFields bool                   `protobuf:"varint,2,opt,name=capture_unrecognized_fields,json=captureUnrecognizedFields,proto3" json:"capture_unrecognized_fields,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_pico_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pico_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_pico_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOptions) GetAlwaysPresent() bool {
	if x != nil {
		return x.AlwaysPresent
	}
	return false
}

func (x *MessageOptions) GetCaptureUnrecognizedFields() bool {
	if x != nil {
		return x.CaptureUnrecognizedFields
	}
	return false
}

type FieldOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AlwaysPresent   bool                   `protobuf:"varint,1,opt,name=always_present,json=alwaysPresent,proto3" json:"always_present,omitempty"`
	CustomType      string                 `protobuf:"bytes,2,opt,name=custom_type,json=customType,proto3" json:"custom_type,omitempty"`
	CustomSerialize string                 `protobuf:"bytes,3,opt,name=custom_serialize,json=customSerialize,proto3" json:"custom_serialize,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_pico_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pico_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_pico_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOptions) GetAlwaysPresent() bool {
	if x != nil {
		return x.AlwaysPresent
	}
	return false
}

func (x *FieldOptions) GetCustomType() string {
	if x != nil {
		return x.CustomType
	}
	return ""
}

func (x *FieldOptions) GetCustomSerialize() string {
	if x != nil {
		return x.CustomSerialize
	}
	return ""
}

var file_pico_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         28980,
		Name:          "pico.message",
		Tag:           "bytes,28980,opt,name=message",
		Filename:      "pico.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         28980,
		Name:          "pico.field",
		Tag:           "bytes,28980,opt,name=field",
		Filename:      "pico.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional pico.MessageOptions message = 28980;
	E_Message = &file_pico_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional pico.FieldOptions field = 28980;
	E_Field = &file_pico_proto_extTypes[1]
)

var File_pico_proto protoreflect.FileDescriptor

const file_pico_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pico.proto\x12\x04pico\x1a google/protobuf/descriptor.proto\"w\n" +
	"\x0eMessageOptions\x12%\n" +
	"\x0ealways_present\x18\x01 \x01(\bR\ralwaysPresent\x12>\n" +
	"\x1bcapture_unrecognized_fields\x18\x02 \x01(\bR\x19captureUnrecognizedFields\"\x81\x01\n" +
	"\fFieldOptions\x12%\n" +
	"\x0ealways_present\x18\x01 \x01(\bR\ralwaysPresent\x12\x1f\n" +
	"\vcustom_type\x18\x02 \x01(\tR\n" +
	"customType\x12)\n" +
	"\x10custom_serialize\x18\x03 \x01(\tR\x0fcustomSerialize:Q\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xb4\xe2\x01 \x01(\v2\x14.pico.MessageOptionsR\amessage:I\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xb4\xe2\x01 \x01(\v2\x12.pico.FieldOptionsR\x05fieldB\x17Z\x15storj.io/picobuf;mainb\x06proto3"

var (
	file_pico_proto_rawDescOnce sync.Once
	file_pico_proto_rawDescData []byte
)

func file_pico_proto_rawDescGZIP() []byte {
	file_pico_proto_rawDescOnce.Do(func() {
		file_pico_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pico_proto_rawDesc), len(file_pico_proto_rawDesc)))
	})
	return file_pico_proto_rawDescData
}

var file_pico_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pico_proto_goTypes = []any{
	(*MessageOptions)(nil),              // 0: pico.MessageOptions
	(*FieldOptions)(nil),                // 1: pico.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_pico_proto_depIdxs = []int32{
	2, // 0: pico.message:extendee -> google.protobuf.MessageOptions
	3, // 1: pico.field:extendee -> google.protobuf.FieldOptions
	0, // 2: pico.message:type_name -> pico.MessageOptions
	1, // 3: pico.field:type_name -> pico.FieldOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pico_proto_init() }
func file_pico_proto_init() {
	if File_pico_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pico_proto_rawDesc), len(file_pico_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_pico_proto_goTypes,
		DependencyIndexes: file_pico_proto_depIdxs,
		MessageInfos:      file_pico_proto_msgTypes,
		ExtensionInfos:    file_pico_proto_extTypes,
	}.Build()
	File_pico_proto = out.File
	file_pico_proto_goTypes = nil
	file_pico_proto_depIdxs = nil
}
