// Copyright (C) 2026 Storj Labs, Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: proto2.proto

package prot2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_READY       State = 1
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_READY",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_READY":       1,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto2_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto2_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *State) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = State(num)
	return nil
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto2_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        *int32                 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Text          *string                `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	State         *State                 `protobuf:"varint,4,opt,name=state,enum=presencecompat.proto2.State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto2_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetNumber() int32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetState() State {
	if x != nil && x.State != nil {
		return *x.State
	}
	return State_STATE_UNSPECIFIED
}

var File_proto2_proto protoreflect.FileDescriptor

const file_proto2_proto_rawDesc = "" +
	"\n" +
	"\fproto2.proto\x12\x15presencecompat.proto2\"}\n" +
	"\aMessage\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.presencecompat.proto2.StateR\x05state*/\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATE_READY\x10\x01"

var (
	file_proto2_proto_rawDescOnce sync.Once
	file_proto2_proto_rawDescData []byte
)

func file_proto2_proto_rawDescGZIP() []byte {
	file_proto2_proto_rawDescOnce.Do(func() {
		file_proto2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto2_proto_rawDesc), len(file_proto2_proto_rawDesc)))
	})
	return file_proto2_proto_rawDescData
}

var file_proto2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto2_proto_goTypes = []any{
	(State)(0),      // 0: presencecompat.proto2.State
	(*Message)(nil), // 1: presencecompat.proto2.Message
}
var file_proto2_proto_depIdxs = []int32{
	0, // 0: presencecompat.proto2.Message.state:type_name -> presencecompat.proto2.State
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto2_proto_init() }
func file_proto2_proto_init() {
	if File_proto2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto2_proto_rawDesc), len(file_proto2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto2_proto_goTypes,
		DependencyIndexes: file_proto2_proto_depIdxs,
		EnumInfos:         file_proto2_proto_enumTypes,
		MessageInfos:      file_proto2_proto_msgTypes,
	}.Build()
	File_proto2_proto = out.File
	file_proto2_proto_goTypes = nil
	file_proto2_proto_depIdxs = nil
}
