// Code generated by protoc-gen-pico. DO NOT EDIT.
// source: profile.proto
//
// versions:
//     protoc-gen-pico: dev
//     protoc:          v7.35.1

package perftest

import (
	picobuf "storj.io/picobuf"
)

type Profile struct {
	SampleType        []*ValueType `json:"sample_type,omitzero"`
	Sample            []*Sample    `json:"sample,omitzero"`
	Mapping           []*Mapping   `json:"mapping,omitzero"`
	Location          []*Location  `json:"location,omitzero"`
	Function          []*Function  `json:"function,omitzero"`
	StringTable       []string     `json:"string_table,omitzero"`
	DropFrames        int64        `json:"drop_frames,omitzero"`
	KeepFrames        int64        `json:"keep_frames,omitzero"`
	TimeNanos         int64        `json:"time_nanos,omitzero"`
	DurationNanos     int64        `json:"duration_nanos,omitzero"`
	PeriodType        *ValueType   `json:"period_type,omitzero"`
	Period            int64        `json:"period,omitzero"`
	Comment           []int64      `json:"comment,omitzero"`
	DefaultSampleType int64        `json:"default_sample_type,omitzero"`
}

func (m *Profile) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	for _, x := range m.SampleType {
		c.AlwaysMessage(1, x.Encode)
	}
	for _, x := range m.Sample {
		c.AlwaysMessage(2, x.Encode)
	}
	for _, x := range m.Mapping {
		c.AlwaysMessage(3, x.Encode)
	}
	for _, x := range m.Location {
		c.AlwaysMessage(4, x.Encode)
	}
	for _, x := range m.Function {
		c.AlwaysMessage(5, x.Encode)
	}
	c.RepeatedString(6, &m.StringTable)
	c.Int64(7, &m.DropFrames)
	c.Int64(8, &m.KeepFrames)
	c.Int64(9, &m.TimeNanos)
	c.Int64(10, &m.DurationNanos)
	c.Message(11, m.PeriodType.Encode)
	c.Int64(12, &m.Period)
	c.RepeatedInt64(13, &m.Comment)
	c.Int64(14, &m.DefaultSampleType)
	return true
}

func (m *Profile) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.RepeatedMessage(1, func(c *picobuf.Decoder) {
		x := new(ValueType)
		c.Loop(x.Decode)
		m.SampleType = append(m.SampleType, x)
	})
	c.RepeatedMessage(2, func(c *picobuf.Decoder) {
		x := new(Sample)
		c.Loop(x.Decode)
		m.Sample = append(m.Sample, x)
	})
	c.RepeatedMessage(3, func(c *picobuf.Decoder) {
		x := new(Mapping)
		c.Loop(x.Decode)
		m.Mapping = append(m.Mapping, x)
	})
	c.RepeatedMessage(4, func(c *picobuf.Decoder) {
		x := new(Location)
		c.Loop(x.Decode)
		m.Location = append(m.Location, x)
	})
	c.RepeatedMessage(5, func(c *picobuf.Decoder) {
		x := new(Function)
		c.Loop(x.Decode)
		m.Function = append(m.Function, x)
	})
	c.RepeatedString(6, &m.StringTable)
	c.Int64(7, &m.DropFrames)
	c.Int64(8, &m.KeepFrames)
	c.Int64(9, &m.TimeNanos)
	c.Int64(10, &m.DurationNanos)
	c.Message(11, func(c *picobuf.Decoder) {
		if m.PeriodType == nil {
			m.PeriodType = new(ValueType)
		}
		m.PeriodType.Decode(c)
	})
	c.Int64(12, &m.Period)
	c.RepeatedInt64(13, &m.Comment)
	c.Int64(14, &m.DefaultSampleType)
}

type ValueType struct {
	Type int64 `json:"type,omitzero"`
	Unit int64 `json:"unit,omitzero"`
}

func (m *ValueType) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.Int64(1, &m.Type)
	c.Int64(2, &m.Unit)
	return true
}

func (m *ValueType) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.Int64(1, &m.Type)
	c.Int64(2, &m.Unit)
}

type Sample struct {
	LocationId []uint64 `json:"location_id,omitzero"`
	Value      []int64  `json:"value,omitzero"`
	Label      []*Label `json:"label,omitzero"`
}

func (m *Sample) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.RepeatedUint64(1, &m.LocationId)
	c.RepeatedInt64(2, &m.Value)
	for _, x := range m.Label {
		c.AlwaysMessage(3, x.Encode)
	}
	return true
}

func (m *Sample) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.RepeatedUint64(1, &m.LocationId)
	c.RepeatedInt64(2, &m.Value)
	c.RepeatedMessage(3, func(c *picobuf.Decoder) {
		x := new(Label)
		c.Loop(x.Decode)
		m.Label = append(m.Label, x)
	})
}

type Label struct {
	Key     int64 `json:"key,omitzero"`
	Str     int64 `json:"str,omitzero"`
	Num     int64 `json:"num,omitzero"`
	NumUnit int64 `json:"num_unit,omitzero"`
}

func (m *Label) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.Int64(1, &m.Key)
	c.Int64(2, &m.Str)
	c.Int64(3, &m.Num)
	c.Int64(4, &m.NumUnit)
	return true
}

func (m *Label) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.Int64(1, &m.Key)
	c.Int64(2, &m.Str)
	c.Int64(3, &m.Num)
	c.Int64(4, &m.NumUnit)
}

type Mapping struct {
	Id              uint64 `json:"id,omitzero"`
	MemoryStart     uint64 `json:"memory_start,omitzero"`
	MemoryLimit     uint64 `json:"memory_limit,omitzero"`
	FileOffset      uint64 `json:"file_offset,omitzero"`
	Filename        int64  `json:"filename,omitzero"`
	BuildId         int64  `json:"build_id,omitzero"`
	HasFunctions    bool   `json:"has_functions,omitzero"`
	HasFilenames    bool   `json:"has_filenames,omitzero"`
	HasLineNumbers  bool   `json:"has_line_numbers,omitzero"`
	HasInlineFrames bool   `json:"has_inline_frames,omitzero"`
}

func (m *Mapping) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.Uint64(1, &m.Id)
	c.Uint64(2, &m.MemoryStart)
	c.Uint64(3, &m.MemoryLimit)
	c.Uint64(4, &m.FileOffset)
	c.Int64(5, &m.Filename)
	c.Int64(6, &m.BuildId)
	c.Bool(7, &m.HasFunctions)
	c.Bool(8, &m.HasFilenames)
	c.Bool(9, &m.HasLineNumbers)
	c.Bool(10, &m.HasInlineFrames)
	return true
}

func (m *Mapping) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.Uint64(1, &m.Id)
	c.Uint64(2, &m.MemoryStart)
	c.Uint64(3, &m.MemoryLimit)
	c.Uint64(4, &m.FileOffset)
	c.Int64(5, &m.Filename)
	c.Int64(6, &m.BuildId)
	c.Bool(7, &m.HasFunctions)
	c.Bool(8, &m.HasFilenames)
	c.Bool(9, &m.HasLineNumbers)
	c.Bool(10, &m.HasInlineFrames)
}

type Location struct {
	Id        uint64  `json:"id,omitzero"`
	MappingId uint64  `json:"mapping_id,omitzero"`
	Address   uint64  `json:"address,omitzero"`
	Line      []*Line `json:"line,omitzero"`
	IsFolded  bool    `json:"is_folded,omitzero"`
}

func (m *Location) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.Uint64(1, &m.Id)
	c.Uint64(2, &m.MappingId)
	c.Uint64(3, &m.Address)
	for _, x := range m.Line {
		c.AlwaysMessage(4, x.Encode)
	}
	c.Bool(5, &m.IsFolded)
	return true
}

func (m *Location) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.Uint64(1, &m.Id)
	c.Uint64(2, &m.MappingId)
	c.Uint64(3, &m.Address)
	c.RepeatedMessage(4, func(c *picobuf.Decoder) {
		x := new(Line)
		c.Loop(x.Decode)
		m.Line = append(m.Line, x)
	})
	c.Bool(5, &m.IsFolded)
}

type Line struct {
	FunctionId uint64 `json:"function_id,omitzero"`
	Line       int64  `json:"line,omitzero"`
	Column     int64  `json:"column,omitzero"`
}

func (m *Line) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.Uint64(1, &m.FunctionId)
	c.Int64(2, &m.Line)
	c.Int64(3, &m.Column)
	return true
}

func (m *Line) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.Uint64(1, &m.FunctionId)
	c.Int64(2, &m.Line)
	c.Int64(3, &m.Column)
}

type Function struct {
	Id         uint64 `json:"id,omitzero"`
	Name       int64  `json:"name,omitzero"`
	SystemName int64  `json:"system_name,omitzero"`
	Filename   int64  `json:"filename,omitzero"`
	StartLine  int64  `json:"start_line,omitzero"`
}

func (m *Function) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.Uint64(1, &m.Id)
	c.Int64(2, &m.Name)
	c.Int64(3, &m.SystemName)
	c.Int64(4, &m.Filename)
	c.Int64(5, &m.StartLine)
	return true
}

func (m *Function) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.Uint64(1, &m.Id)
	c.Int64(2, &m.Name)
	c.Int64(3, &m.SystemName)
	c.Int64(4, &m.Filename)
	c.Int64(5, &m.StartLine)
}
