// Copyright (C) 2026 Storj Labs Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: schema.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	_ "storj.io/picobuf"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_READY       State = 1
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_READY",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_READY":       1,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        *int32                 `protobuf:"varint,1,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Text          *string                `protobuf:"bytes,2,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	State         *State                 `protobuf:"varint,4,opt,name=state,proto3,enum=presencecompat.State,oneof" json:"state,omitempty"`
	Boolean       *bool                  `protobuf:"varint,5,opt,name=boolean,proto3,oneof" json:"boolean,omitempty"`
	Int64Value    *int64                 `protobuf:"varint,6,opt,name=int64_value,json=int64Value,proto3,oneof" json:"int64_value,omitempty"`
	Uint32Value   *uint32                `protobuf:"varint,7,opt,name=uint32_value,json=uint32Value,proto3,oneof" json:"uint32_value,omitempty"`
	Uint64Value   *uint64                `protobuf:"varint,8,opt,name=uint64_value,json=uint64Value,proto3,oneof" json:"uint64_value,omitempty"`
	Sint32Value   *int32                 `protobuf:"zigzag32,9,opt,name=sint32_value,json=sint32Value,proto3,oneof" json:"sint32_value,omitempty"`
	Sint64Value   *int64                 `protobuf:"zigzag64,10,opt,name=sint64_value,json=sint64Value,proto3,oneof" json:"sint64_value,omitempty"`
	Fixed32Value  *uint32                `protobuf:"fixed32,11,opt,name=fixed32_value,json=fixed32Value,proto3,oneof" json:"fixed32_value,omitempty"`
	Fixed64Value  *uint64                `protobuf:"fixed64,12,opt,name=fixed64_value,json=fixed64Value,proto3,oneof" json:"fixed64_value,omitempty"`
	Sfixed32Value *int32                 `protobuf:"fixed32,13,opt,name=sfixed32_value,json=sfixed32Value,proto3,oneof" json:"sfixed32_value,omitempty"`
	Sfixed64Value *int64                 `protobuf:"fixed64,14,opt,name=sfixed64_value,json=sfixed64Value,proto3,oneof" json:"sfixed64_value,omitempty"`
	FloatValue    *float32               `protobuf:"fixed32,15,opt,name=float_value,json=floatValue,proto3,oneof" json:"float_value,omitempty"`
	DoubleValue   *float64               `protobuf:"fixed64,16,opt,name=double_value,json=doubleValue,proto3,oneof" json:"double_value,omitempty"`
	// Types that are valid to be assigned to Selection:
	//
	//	*Message_SelectedState
	//	*Message_SelectedText
	Selection     isMessage_Selection `protobuf_oneof:"selection"`
	Numbers       []int32             `protobuf:"varint,19,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Names         map[string]string   `protobuf:"bytes,20,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AlwaysText    *string             `protobuf:"bytes,21,opt,name=always_text,json=alwaysText,proto3,oneof" json:"always_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetNumber() int32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetState() State {
	if x != nil && x.State != nil {
		return *x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *Message) GetBoolean() bool {
	if x != nil && x.Boolean != nil {
		return *x.Boolean
	}
	return false
}

func (x *Message) GetInt64Value() int64 {
	if x != nil && x.Int64Value != nil {
		return *x.Int64Value
	}
	return 0
}

func (x *Message) GetUint32Value() uint32 {
	if x != nil && x.Uint32Value != nil {
		return *x.Uint32Value
	}
	return 0
}

func (x *Message) GetUint64Value() uint64 {
	if x != nil && x.Uint64Value != nil {
		return *x.Uint64Value
	}
	return 0
}

func (x *Message) GetSint32Value() int32 {
	if x != nil && x.Sint32Value != nil {
		return *x.Sint32Value
	}
	return 0
}

func (x *Message) GetSint64Value() int64 {
	if x != nil && x.Sint64Value != nil {
		return *x.Sint64Value
	}
	return 0
}

func (x *Message) GetFixed32Value() uint32 {
	if x != nil && x.Fixed32Value != nil {
		return *x.Fixed32Value
	}
	return 0
}

func (x *Message) GetFixed64Value() uint64 {
	if x != nil && x.Fixed64Value != nil {
		return *x.Fixed64Value
	}
	return 0
}

func (x *Message) GetSfixed32Value() int32 {
	if x != nil && x.Sfixed32Value != nil {
		return *x.Sfixed32Value
	}
	return 0
}

func (x *Message) GetSfixed64Value() int64 {
	if x != nil && x.Sfixed64Value != nil {
		return *x.Sfixed64Value
	}
	return 0
}

func (x *Message) GetFloatValue() float32 {
	if x != nil && x.FloatValue != nil {
		return *x.FloatValue
	}
	return 0
}

func (x *Message) GetDoubleValue() float64 {
	if x != nil && x.DoubleValue != nil {
		return *x.DoubleValue
	}
	return 0
}

func (x *Message) GetSelection() isMessage_Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *Message) GetSelectedState() State {
	if x != nil {
		if x, ok := x.Selection.(*Message_SelectedState); ok {
			return x.SelectedState
		}
	}
	return State_STATE_UNSPECIFIED
}

func (x *Message) GetSelectedText() string {
	if x != nil {
		if x, ok := x.Selection.(*Message_SelectedText); ok {
			return x.SelectedText
		}
	}
	return ""
}

func (x *Message) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *Message) GetNames() map[string]string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Message) GetAlwaysText() string {
	if x != nil && x.AlwaysText != nil {
		return *x.AlwaysText
	}
	return ""
}

type isMessage_Selection interface {
	isMessage_Selection()
}

type Message_SelectedState struct {
	SelectedState State `protobuf:"varint,17,opt,name=selected_state,json=selectedState,proto3,enum=presencecompat.State,oneof"`
}

type Message_SelectedText struct {
	SelectedText string `protobuf:"bytes,18,opt,name=selected_text,json=selectedText,proto3,oneof"`
}

func (*Message_SelectedState) isMessage_Selection() {}

func (*Message_SelectedText) isMessage_Selection() {}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\x0epresencecompat\x1a\n" +
	"pico.proto\"\x9b\t\n" +
	"\aMessage\x12\x1b\n" +
	"\x06number\x18\x01 \x01(\x05H\x01R\x06number\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x02 \x01(\tH\x02R\x04text\x88\x01\x01\x12\x17\n" +
	"\x04data\x18\x03 \x01(\fH\x03R\x04data\x88\x01\x01\x120\n" +
	"\x05state\x18\x04 \x01(\x0e2\x15.presencecompat.StateH\x04R\x05state\x88\x01\x01\x12\x1d\n" +
	"\aboolean\x18\x05 \x01(\bH\x05R\aboolean\x88\x01\x01\x12$\n" +
	"\vint64_value\x18\x06 \x01(\x03H\x06R\n" +
	"int64Value\x88\x01\x01\x12&\n" +
	"\fuint32_value\x18\a \x01(\rH\aR\vuint32Value\x88\x01\x01\x12&\n" +
	"\fuint64_value\x18\b \x01(\x04H\bR\vuint64Value\x88\x01\x01\x12&\n" +
	"\fsint32_value\x18\t \x01(\x11H\tR\vsint32Value\x88\x01\x01\x12&\n" +
	"\fsint64_value\x18\n" +
	" \x01(\x12H\n" +
	"R\vsint64Value\x88\x01\x01\x12(\n" +
	"\rfixed32_value\x18\v \x01(\aH\vR\ffixed32Value\x88\x01\x01\x12(\n" +
	"\rfixed64_value\x18\f \x01(\x06H\fR\ffixed64Value\x88\x01\x01\x12*\n" +
	"\x0esfixed32_value\x18\r \x01(\x0fH\rR\rsfixed32Value\x88\x01\x01\x12*\n" +
	"\x0esfixed64_value\x18\x0e \x01(\x10H\x0eR\rsfixed64Value\x88\x01\x01\x12$\n" +
	"\vfloat_value\x18\x0f \x01(\x02H\x0fR\n" +
	"floatValue\x88\x01\x01\x12&\n" +
	"\fdouble_value\x18\x10 \x01(\x01H\x10R\vdoubleValue\x88\x01\x01\x12>\n" +
	"\x0eselected_state\x18\x11 \x01(\x0e2\x15.presencecompat.StateH\x00R\rselectedState\x12%\n" +
	"\rselected_text\x18\x12 \x01(\tH\x00R\fselectedText\x12\x18\n" +
	"\anumbers\x18\x13 \x03(\x05R\anumbers\x128\n" +
	"\x05names\x18\x14 \x03(\v2\".presencecompat.Message.NamesEntryR\x05names\x12,\n" +
	"\valways_text\x18\x15 \x01(\tB\x06\xa2\x93\x0e\x02\b\x01H\x11R\n" +
	"alwaysText\x88\x01\x01\x1a8\n" +
	"\n" +
	"NamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\tselectionB\t\n" +
	"\a_numberB\a\n" +
	"\x05_textB\a\n" +
	"\x05_dataB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_booleanB\x0e\n" +
	"\f_int64_valueB\x0f\n" +
	"\r_uint32_valueB\x0f\n" +
	"\r_uint64_valueB\x0f\n" +
	"\r_sint32_valueB\x0f\n" +
	"\r_sint64_valueB\x10\n" +
	"\x0e_fixed32_valueB\x10\n" +
	"\x0e_fixed64_valueB\x11\n" +
	"\x0f_sfixed32_valueB\x11\n" +
	"\x0f_sfixed64_valueB\x0e\n" +
	"\f_float_valueB\x0f\n" +
	"\r_double_valueB\x0e\n" +
	"\f_always_text*/\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATE_READY\x10\x01b\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_proto_goTypes = []any{
	(State)(0),      // 0: presencecompat.State
	(*Message)(nil), // 1: presencecompat.Message
	nil,             // 2: presencecompat.Message.NamesEntry
}
var file_schema_proto_depIdxs = []int32{
	0, // 0: presencecompat.Message.state:type_name -> presencecompat.State
	0, // 1: presencecompat.Message.selected_state:type_name -> presencecompat.State
	2, // 2: presencecompat.Message.names:type_name -> presencecompat.Message.NamesEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	file_schema_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_SelectedState)(nil),
		(*Message_SelectedText)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		EnumInfos:         file_schema_proto_enumTypes,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
