// Code generated by protoc-gen-pico. DO NOT EDIT.
// source: schema.proto
//
// versions:
//     protoc-gen-pico: v0.0.5-0.20260818150459-c5e6f3459ebe+dirty
//     protoc:          v7.35.1

package pico

import (
	picobuf "storj.io/picobuf"
	picowire "storj.io/picobuf/picowire"
	strconv "strconv"
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_READY       State = 1
)

func (m State) String() string {
	switch m {
	case State_STATE_UNSPECIFIED:
		return "STATE_UNSPECIFIED"
	case State_STATE_READY:
		return "STATE_READY"
	default:
		return "State(" + strconv.Itoa(int(m)) + ")"
	}
}

type Message struct {
	Number        *int32   `json:"number,omitzero"`
	Text          *string  `json:"text,omitzero"`
	Data          *[]byte  `json:"data,omitzero"`
	State         *State   `json:"state,omitzero"`
	Boolean       *bool    `json:"boolean,omitzero"`
	Int64Value    *int64   `json:"int64_value,omitzero"`
	Uint32Value   *uint32  `json:"uint32_value,omitzero"`
	Uint64Value   *uint64  `json:"uint64_value,omitzero"`
	Sint32Value   *int32   `json:"sint32_value,omitzero"`
	Sint64Value   *int64   `json:"sint64_value,omitzero"`
	Fixed32Value  *uint32  `json:"fixed32_value,omitzero"`
	Fixed64Value  *uint64  `json:"fixed64_value,omitzero"`
	Sfixed32Value *int32   `json:"sfixed32_value,omitzero"`
	Sfixed64Value *int64   `json:"sfixed64_value,omitzero"`
	FloatValue    *float32 `json:"float_value,omitzero"`
	DoubleValue   *float64 `json:"double_value,omitzero"`
	// Types that are assignable to Selection:
	//
	//	*Message_SelectedState
	//	*Message_SelectedText
	Selection  isMessage_Selection
	Numbers    []int32           `json:"numbers,omitzero"`
	Names      map[string]string `json:"names,omitzero"`
	AlwaysText string            `json:"always_text,omitzero"`
}

func (m *Message) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	if m.Number != nil {
		c.AlwaysInt32(1, m.Number)
	}
	if m.Text != nil {
		c.AlwaysString(2, m.Text)
	}
	if m.Data != nil {
		c.AlwaysBytes(3, m.Data)
	}
	if m.State != nil {
		c.AlwaysInt32(4, (*int32)(m.State))
	}
	if m.Boolean != nil {
		c.AlwaysBool(5, m.Boolean)
	}
	if m.Int64Value != nil {
		c.AlwaysInt64(6, m.Int64Value)
	}
	if m.Uint32Value != nil {
		c.AlwaysUint32(7, m.Uint32Value)
	}
	if m.Uint64Value != nil {
		c.AlwaysUint64(8, m.Uint64Value)
	}
	if m.Sint32Value != nil {
		c.AlwaysSint32(9, m.Sint32Value)
	}
	if m.Sint64Value != nil {
		c.AlwaysSint64(10, m.Sint64Value)
	}
	if m.Fixed32Value != nil {
		c.AlwaysFixed32(11, m.Fixed32Value)
	}
	if m.Fixed64Value != nil {
		c.AlwaysFixed64(12, m.Fixed64Value)
	}
	if m.Sfixed32Value != nil {
		c.AlwaysSfixed32(13, m.Sfixed32Value)
	}
	if m.Sfixed64Value != nil {
		c.AlwaysSfixed64(14, m.Sfixed64Value)
	}
	if m.FloatValue != nil {
		c.AlwaysFloat(15, m.FloatValue)
	}
	if m.DoubleValue != nil {
		c.AlwaysDouble(16, m.DoubleValue)
	}
	if m, ok := m.Selection.(*Message_SelectedState); ok {
		c.AlwaysInt32(17, (*int32)(&m.SelectedState))
	}
	if m, ok := m.Selection.(*Message_SelectedText); ok {
		c.AlwaysString(18, &m.SelectedText)
	}
	c.RepeatedInt32(19, &m.Numbers)
	(*picowire.MapStringString)(&m.Names).PicoEncode(c, 20)
	c.String(21, &m.AlwaysText)
	return true
}

func (m *Message) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	if c.PendingField() == 1 {
		m.Number = new(int32)
		c.Int32(1, m.Number)
	}
	if c.PendingField() == 2 {
		m.Text = new(string)
		c.String(2, m.Text)
	}
	if c.PendingField() == 3 {
		m.Data = new([]byte)
		c.Bytes(3, m.Data)
	}
	if c.PendingField() == 4 {
		m.State = new(State)
		c.Int32(4, (*int32)(m.State))
	}
	if c.PendingField() == 5 {
		m.Boolean = new(bool)
		c.Bool(5, m.Boolean)
	}
	if c.PendingField() == 6 {
		m.Int64Value = new(int64)
		c.Int64(6, m.Int64Value)
	}
	if c.PendingField() == 7 {
		m.Uint32Value = new(uint32)
		c.Uint32(7, m.Uint32Value)
	}
	if c.PendingField() == 8 {
		m.Uint64Value = new(uint64)
		c.Uint64(8, m.Uint64Value)
	}
	if c.PendingField() == 9 {
		m.Sint32Value = new(int32)
		c.Sint32(9, m.Sint32Value)
	}
	if c.PendingField() == 10 {
		m.Sint64Value = new(int64)
		c.Sint64(10, m.Sint64Value)
	}
	if c.PendingField() == 11 {
		m.Fixed32Value = new(uint32)
		c.Fixed32(11, m.Fixed32Value)
	}
	if c.PendingField() == 12 {
		m.Fixed64Value = new(uint64)
		c.Fixed64(12, m.Fixed64Value)
	}
	if c.PendingField() == 13 {
		m.Sfixed32Value = new(int32)
		c.Sfixed32(13, m.Sfixed32Value)
	}
	if c.PendingField() == 14 {
		m.Sfixed64Value = new(int64)
		c.Sfixed64(14, m.Sfixed64Value)
	}
	if c.PendingField() == 15 {
		m.FloatValue = new(float32)
		c.Float(15, m.FloatValue)
	}
	if c.PendingField() == 16 {
		m.DoubleValue = new(float64)
		c.Double(16, m.DoubleValue)
	}
	if c.PendingField() == 17 {
		var x *Message_SelectedState
		if z, ok := m.Selection.(*Message_SelectedState); ok {
			x = z
		} else {
			x = new(Message_SelectedState)
			m.Selection = x
		}
		m := x
		c.Int32(17, (*int32)(&m.SelectedState))
	}
	if c.PendingField() == 18 {
		var x *Message_SelectedText
		if z, ok := m.Selection.(*Message_SelectedText); ok {
			x = z
		} else {
			x = new(Message_SelectedText)
			m.Selection = x
		}
		m := x
		c.String(18, &m.SelectedText)
	}
	c.RepeatedInt32(19, &m.Numbers)
	(*picowire.MapStringString)(&m.Names).PicoDecode(c, 20)
	c.String(21, &m.AlwaysText)
}

type isMessage_Selection interface{ isMessage_Selection() }

type Message_SelectedState struct {
	SelectedState State
}

type Message_SelectedText struct {
	SelectedText string
}

func (*Message_SelectedState) isMessage_Selection() {}
func (*Message_SelectedText) isMessage_Selection()  {}
