// Copyright (C) 2026 Storj Labs Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: editions.proto

package editionprot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExplicitNumber *int32                 `protobuf:"varint,1,opt,name=explicit_number,json=explicitNumber" json:"explicit_number,omitempty"`
	ExplicitText   *string                `protobuf:"bytes,2,opt,name=explicit_text,json=explicitText" json:"explicit_text,omitempty"`
	ExplicitData   []byte                 `protobuf:"bytes,3,opt,name=explicit_data,json=explicitData" json:"explicit_data,omitempty"`
	ImplicitNumber int32                  `protobuf:"varint,4,opt,name=implicit_number,json=implicitNumber" json:"implicit_number,omitempty"`
	ImplicitText   string                 `protobuf:"bytes,5,opt,name=implicit_text,json=implicitText" json:"implicit_text,omitempty"`
	ImplicitData   []byte                 `protobuf:"bytes,6,opt,name=implicit_data,json=implicitData" json:"implicit_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_editions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_editions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_editions_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetExplicitNumber() int32 {
	if x != nil && x.ExplicitNumber != nil {
		return *x.ExplicitNumber
	}
	return 0
}

func (x *Message) GetExplicitText() string {
	if x != nil && x.ExplicitText != nil {
		return *x.ExplicitText
	}
	return ""
}

func (x *Message) GetExplicitData() []byte {
	if x != nil {
		return x.ExplicitData
	}
	return nil
}

func (x *Message) GetImplicitNumber() int32 {
	if x != nil {
		return x.ImplicitNumber
	}
	return 0
}

func (x *Message) GetImplicitText() string {
	if x != nil {
		return x.ImplicitText
	}
	return ""
}

func (x *Message) GetImplicitData() []byte {
	if x != nil {
		return x.ImplicitData
	}
	return nil
}

var File_editions_proto protoreflect.FileDescriptor

const file_editions_proto_rawDesc = "" +
	"\n" +
	"\x0eeditions.proto\x12\x17presencecompat.editions\"\x84\x02\n" +
	"\aMessage\x12'\n" +
	"\x0fexplicit_number\x18\x01 \x01(\x05R\x0eexplicitNumber\x12#\n" +
	"\rexplicit_text\x18\x02 \x01(\tR\fexplicitText\x12#\n" +
	"\rexplicit_data\x18\x03 \x01(\fR\fexplicitData\x12.\n" +
	"\x0fimplicit_number\x18\x04 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x0eimplicitNumber\x12*\n" +
	"\rimplicit_text\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\fimplicitText\x12*\n" +
	"\rimplicit_data\x18\x06 \x01(\fB\x05\xaa\x01\x02\b\x02R\fimplicitDatab\beditionsp\xe8\a"

var (
	file_editions_proto_rawDescOnce sync.Once
	file_editions_proto_rawDescData []byte
)

func file_editions_proto_rawDescGZIP() []byte {
	file_editions_proto_rawDescOnce.Do(func() {
		file_editions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_editions_proto_rawDesc), len(file_editions_proto_rawDesc)))
	})
	return file_editions_proto_rawDescData
}

var file_editions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_editions_proto_goTypes = []any{
	(*Message)(nil), // 0: presencecompat.editions.Message
}
var file_editions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_editions_proto_init() }
func file_editions_proto_init() {
	if File_editions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_editions_proto_rawDesc), len(file_editions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_editions_proto_goTypes,
		DependencyIndexes: file_editions_proto_depIdxs,
		MessageInfos:      file_editions_proto_msgTypes,
	}.Build()
	File_editions_proto = out.File
	file_editions_proto_goTypes = nil
	file_editions_proto_depIdxs = nil
}
