// Copyright (C) 2026 Storj Labs, Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: editions.proto

package editionprot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClosedState int32

const (
	ClosedState_CLOSED_STATE_UNSPECIFIED ClosedState = 0
	ClosedState_CLOSED_STATE_READY       ClosedState = 1
)

// Enum value maps for ClosedState.
var (
	ClosedState_name = map[int32]string{
		0: "CLOSED_STATE_UNSPECIFIED",
		1: "CLOSED_STATE_READY",
	}
	ClosedState_value = map[string]int32{
		"CLOSED_STATE_UNSPECIFIED": 0,
		"CLOSED_STATE_READY":       1,
	}
)

func (x ClosedState) Enum() *ClosedState {
	p := new(ClosedState)
	*p = x
	return p
}

func (x ClosedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClosedState) Descriptor() protoreflect.EnumDescriptor {
	return file_editions_proto_enumTypes[0].Descriptor()
}

func (ClosedState) Type() protoreflect.EnumType {
	return &file_editions_proto_enumTypes[0]
}

func (x ClosedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClosedState.Descriptor instead.
func (ClosedState) EnumDescriptor() ([]byte, []int) {
	return file_editions_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExplicitNumber  *int32                 `protobuf:"varint,1,opt,name=explicit_number,json=explicitNumber" json:"explicit_number,omitempty"`
	ExplicitText    *string                `protobuf:"bytes,2,opt,name=explicit_text,json=explicitText" json:"explicit_text,omitempty"`
	ExplicitData    []byte                 `protobuf:"bytes,3,opt,name=explicit_data,json=explicitData" json:"explicit_data,omitempty"`
	ImplicitNumber  int32                  `protobuf:"varint,4,opt,name=implicit_number,json=implicitNumber" json:"implicit_number,omitempty"`
	ImplicitText    string                 `protobuf:"bytes,5,opt,name=implicit_text,json=implicitText" json:"implicit_text,omitempty"`
	ImplicitData    []byte                 `protobuf:"bytes,6,opt,name=implicit_data,json=implicitData" json:"implicit_data,omitempty"`
	PackedNumbers   []int32                `protobuf:"varint,7,rep,packed,name=packed_numbers,json=packedNumbers" json:"packed_numbers,omitempty"`
	ExpandedNumbers []int32                `protobuf:"varint,8,rep,name=expanded_numbers,json=expandedNumbers" json:"expanded_numbers,omitempty"`
	Nested          *Nested                `protobuf:"group,9,opt,name=Nested,json=nested" json:"nested,omitempty"`
	ClosedState     *ClosedState           `protobuf:"varint,10,opt,name=closed_state,json=closedState,enum=presencecompat.editions.ClosedState" json:"closed_state,omitempty"`
	ClosedStates    []ClosedState          `protobuf:"varint,11,rep,packed,name=closed_states,json=closedStates,enum=presencecompat.editions.ClosedState" json:"closed_states,omitempty"`
	// Types that are valid to be assigned to ClosedSelection:
	//
	//	*Message_SelectedClosedState
	ClosedSelection isMessage_ClosedSelection `protobuf_oneof:"closed_selection"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_editions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_editions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_editions_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetExplicitNumber() int32 {
	if x != nil && x.ExplicitNumber != nil {
		return *x.ExplicitNumber
	}
	return 0
}

func (x *Message) GetExplicitText() string {
	if x != nil && x.ExplicitText != nil {
		return *x.ExplicitText
	}
	return ""
}

func (x *Message) GetExplicitData() []byte {
	if x != nil {
		return x.ExplicitData
	}
	return nil
}

func (x *Message) GetImplicitNumber() int32 {
	if x != nil {
		return x.ImplicitNumber
	}
	return 0
}

func (x *Message) GetImplicitText() string {
	if x != nil {
		return x.ImplicitText
	}
	return ""
}

func (x *Message) GetImplicitData() []byte {
	if x != nil {
		return x.ImplicitData
	}
	return nil
}

func (x *Message) GetPackedNumbers() []int32 {
	if x != nil {
		return x.PackedNumbers
	}
	return nil
}

func (x *Message) GetExpandedNumbers() []int32 {
	if x != nil {
		return x.ExpandedNumbers
	}
	return nil
}

func (x *Message) GetNested() *Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Message) GetClosedState() ClosedState {
	if x != nil && x.ClosedState != nil {
		return *x.ClosedState
	}
	return ClosedState_CLOSED_STATE_UNSPECIFIED
}

func (x *Message) GetClosedStates() []ClosedState {
	if x != nil {
		return x.ClosedStates
	}
	return nil
}

func (x *Message) GetClosedSelection() isMessage_ClosedSelection {
	if x != nil {
		return x.ClosedSelection
	}
	return nil
}

func (x *Message) GetSelectedClosedState() ClosedState {
	if x != nil {
		if x, ok := x.ClosedSelection.(*Message_SelectedClosedState); ok {
			return x.SelectedClosedState
		}
	}
	return ClosedState_CLOSED_STATE_UNSPECIFIED
}

type isMessage_ClosedSelection interface {
	isMessage_ClosedSelection()
}

type Message_SelectedClosedState struct {
	SelectedClosedState ClosedState `protobuf:"varint,12,opt,name=selected_closed_state,json=selectedClosedState,enum=presencecompat.editions.ClosedState,oneof"`
}

func (*Message_SelectedClosedState) isMessage_ClosedSelection() {}

type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_editions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_editions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_editions_proto_rawDescGZIP(), []int{1}
}

func (x *Nested) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type RequiredMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequiredNumber *int32                 `protobuf:"varint,1,req,name=required_number,json=requiredNumber" json:"required_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequiredMessage) Reset() {
	*x = RequiredMessage{}
	mi := &file_editions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredMessage) ProtoMessage() {}

func (x *RequiredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_editions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredMessage.ProtoReflect.Descriptor instead.
func (*RequiredMessage) Descriptor() ([]byte, []int) {
	return file_editions_proto_rawDescGZIP(), []int{2}
}

func (x *RequiredMessage) GetRequiredNumber() int32 {
	if x != nil && x.RequiredNumber != nil {
		return *x.RequiredNumber
	}
	return 0
}

type RequiredParent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         *RequiredMessage       `protobuf:"bytes,1,opt,name=child" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredParent) Reset() {
	*x = RequiredParent{}
	mi := &file_editions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredParent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredParent) ProtoMessage() {}

func (x *RequiredParent) ProtoReflect() protoreflect.Message {
	mi := &file_editions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredParent.ProtoReflect.Descriptor instead.
func (*RequiredParent) Descriptor() ([]byte, []int) {
	return file_editions_proto_rawDescGZIP(), []int{3}
}

func (x *RequiredParent) GetChild() *RequiredMessage {
	if x != nil {
		return x.Child
	}
	return nil
}

var File_editions_proto protoreflect.FileDescriptor

const file_editions_proto_rawDesc = "" +
	"\n" +
	"\x0eeditions.proto\x12\x17presencecompat.editions\"\xa1\x05\n" +
	"\aMessage\x12'\n" +
	"\x0fexplicit_number\x18\x01 \x01(\x05R\x0eexplicitNumber\x12#\n" +
	"\rexplicit_text\x18\x02 \x01(\tR\fexplicitText\x12#\n" +
	"\rexplicit_data\x18\x03 \x01(\fR\fexplicitData\x12.\n" +
	"\x0fimplicit_number\x18\x04 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x0eimplicitNumber\x12*\n" +
	"\rimplicit_text\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\fimplicitText\x12*\n" +
	"\rimplicit_data\x18\x06 \x01(\fB\x05\xaa\x01\x02\b\x02R\fimplicitData\x12%\n" +
	"\x0epacked_numbers\x18\a \x03(\x05R\rpackedNumbers\x120\n" +
	"\x10expanded_numbers\x18\b \x03(\x05B\x05\xaa\x01\x02\x18\x02R\x0fexpandedNumbers\x12>\n" +
	"\x06nested\x18\t \x01(\v2\x1f.presencecompat.editions.NestedB\x05\xaa\x01\x02(\x02R\x06nested\x12G\n" +
	"\fclosed_state\x18\n" +
	" \x01(\x0e2$.presencecompat.editions.ClosedStateR\vclosedState\x12I\n" +
	"\rclosed_states\x18\v \x03(\x0e2$.presencecompat.editions.ClosedStateR\fclosedStates\x12Z\n" +
	"\x15selected_closed_state\x18\f \x01(\x0e2$.presencecompat.editions.ClosedStateH\x00R\x13selectedClosedStateB\x12\n" +
	"\x10closed_selection\"\x1e\n" +
	"\x06Nested\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"A\n" +
	"\x0fRequiredMessage\x12.\n" +
	"\x0frequired_number\x18\x01 \x01(\x05B\x05\xaa\x01\x02\b\x03R\x0erequiredNumber\"P\n" +
	"\x0eRequiredParent\x12>\n" +
	"\x05child\x18\x01 \x01(\v2(.presencecompat.editions.RequiredMessageR\x05child*I\n" +
	"\vClosedState\x12\x1c\n" +
	"\x18CLOSED_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CLOSED_STATE_READY\x10\x01\x1a\x04:\x02\x10\x02b\beditionsp\xe8\a"

var (
	file_editions_proto_rawDescOnce sync.Once
	file_editions_proto_rawDescData []byte
)

func file_editions_proto_rawDescGZIP() []byte {
	file_editions_proto_rawDescOnce.Do(func() {
		file_editions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_editions_proto_rawDesc), len(file_editions_proto_rawDesc)))
	})
	return file_editions_proto_rawDescData
}

var file_editions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_editions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_editions_proto_goTypes = []any{
	(ClosedState)(0),        // 0: presencecompat.editions.ClosedState
	(*Message)(nil),         // 1: presencecompat.editions.Message
	(*Nested)(nil),          // 2: presencecompat.editions.Nested
	(*RequiredMessage)(nil), // 3: presencecompat.editions.RequiredMessage
	(*RequiredParent)(nil),  // 4: presencecompat.editions.RequiredParent
}
var file_editions_proto_depIdxs = []int32{
	2, // 0: presencecompat.editions.Message.nested:type_name -> presencecompat.editions.Nested
	0, // 1: presencecompat.editions.Message.closed_state:type_name -> presencecompat.editions.ClosedState
	0, // 2: presencecompat.editions.Message.closed_states:type_name -> presencecompat.editions.ClosedState
	0, // 3: presencecompat.editions.Message.selected_closed_state:type_name -> presencecompat.editions.ClosedState
	3, // 4: presencecompat.editions.RequiredParent.child:type_name -> presencecompat.editions.RequiredMessage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_editions_proto_init() }
func file_editions_proto_init() {
	if File_editions_proto != nil {
		return
	}
	file_editions_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_SelectedClosedState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_editions_proto_rawDesc), len(file_editions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_editions_proto_goTypes,
		DependencyIndexes: file_editions_proto_depIdxs,
		EnumInfos:         file_editions_proto_enumTypes,
		MessageInfos:      file_editions_proto_msgTypes,
	}.Build()
	File_editions_proto = out.File
	file_editions_proto_goTypes = nil
	file_editions_proto_depIdxs = nil
}
