// Code generated by protoc-gen-pico. DO NOT EDIT.
// source: test.proto
//
// versions:
//     protoc-gen-pico: dev
//     protoc:          v7.35.1

package editiontest

import (
	picobuf "storj.io/picobuf"
	picowire "storj.io/picobuf/picowire"
)

type Message struct {
	Unvalidated    *string           `json:"unvalidated,omitzero"`
	Validated      *string           `json:"validated,omitzero"`
	UnvalidatedMap map[string]string `json:"unvalidated_map,omitzero"`
	ValidatedMap   map[string]string `json:"validated_map,omitzero"`
}

func (m *Message) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.WithoutUTF8Validation(func() {
		if m.Unvalidated != nil {
			c.AlwaysString(1, m.Unvalidated)
		}
	})
	if m.Validated != nil {
		c.AlwaysString(2, m.Validated)
	}
	c.WithoutUTF8Validation(func() {
		(*picowire.MapStringString)(&m.UnvalidatedMap).PicoEncode(c, 3)
	})
	(*picowire.MapStringString)(&m.ValidatedMap).PicoEncode(c, 4)
	return true
}

func (m *Message) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.WithoutUTF8Validation(func() {
		if c.PendingField() == 1 {
			m.Unvalidated = new(string)
			c.String(1, m.Unvalidated)
		}
	})
	if c.PendingField() == 2 {
		m.Validated = new(string)
		c.String(2, m.Validated)
	}
	c.WithoutUTF8Validation(func() {
		(*picowire.MapStringString)(&m.UnvalidatedMap).PicoDecode(c, 3)
	})
	(*picowire.MapStringString)(&m.ValidatedMap).PicoDecode(c, 4)
}
