// Code generated by protoc-gen-pico. DO NOT EDIT.
// source: internal/editiontest/test.proto
//
// versions:
//     protoc-gen-pico: v0.0.5-0.20260818121237-1f2775a3dc52+dirty
//     protoc:          v7.35.1

package editiontest

import (
	picobuf "storj.io/picobuf"
)

type Message struct {
	Unvalidated string `json:"unvalidated,omitempty"`
	Validated   string `json:"validated,omitempty"`
}

func (m *Message) Encode(c *picobuf.Encoder) bool {
	if m == nil {
		return false
	}
	c.WithoutUTF8Validation(func() {
		c.String(1, &m.Unvalidated)
	})
	c.String(2, &m.Validated)
	return true
}

func (m *Message) Decode(c *picobuf.Decoder) {
	if m == nil {
		return
	}
	c.WithoutUTF8Validation(func() {
		c.String(1, &m.Unvalidated)
	})
	c.String(2, &m.Validated)
}
