// Copyright (C) 2021 Storj Labs, Inc.
// See LICENSE for copying information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: types.proto

package prot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	_ "storj.io/picobuf"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_UNKNOWN Language = 0
	Language_ENGLISH Language = 1
	Language_SPANISH Language = 3
	Language_FRENCH  Language = 4
	Language_GERMAN  Language = 5
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "UNKNOWN",
		1: "ENGLISH",
		3: "SPANISH",
		4: "FRENCH",
		5: "GERMAN",
	}
	Language_value = map[string]int32{
		"UNKNOWN": 0,
		"ENGLISH": 1,
		"SPANISH": 3,
		"FRENCH":  4,
		"GERMAN":  5,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

type Types struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Int32           int32                  `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64           int64                  `protobuf:"varint,2,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32          uint32                 `protobuf:"varint,3,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64          uint64                 `protobuf:"varint,4,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32          int32                  `protobuf:"zigzag32,5,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64          int64                  `protobuf:"zigzag64,6,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32         uint32                 `protobuf:"fixed32,7,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64         uint64                 `protobuf:"fixed64,8,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32        int32                  `protobuf:"fixed32,9,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64        int64                  `protobuf:"fixed64,10,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Float           float32                `protobuf:"fixed32,11,opt,name=float,proto3" json:"float,omitempty"`
	Double          float64                `protobuf:"fixed64,12,opt,name=double,proto3" json:"double,omitempty"`
	Bool            bool                   `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"`
	String_         string                 `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Bytes           []byte                 `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Message         *Message               `protobuf:"bytes,16,opt,name=message,proto3" json:"message,omitempty"`
	OptionalMessage *OptionalMessage       `protobuf:"bytes,17,opt,name=optional_message,json=optionalMessage,proto3" json:"optional_message,omitempty"`
	Language        Language               `protobuf:"varint,18,opt,name=language,proto3,enum=types.Language" json:"language,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Types) Reset() {
	*x = Types{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Types) ProtoMessage() {}

func (x *Types) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Types.ProtoReflect.Descriptor instead.
func (*Types) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Types) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Types) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *Types) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *Types) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *Types) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *Types) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *Types) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *Types) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *Types) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *Types) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *Types) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *Types) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *Types) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *Types) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *Types) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Types) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Types) GetOptionalMessage() *OptionalMessage {
	if x != nil {
		return x.OptionalMessage
	}
	return nil
}

func (x *Types) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_UNKNOWN
}

type RepeatedTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32         []int32                `protobuf:"varint,1,rep,packed,name=int32,proto3" json:"int32,omitempty"`
	Int64         []int64                `protobuf:"varint,2,rep,packed,name=int64,proto3" json:"int64,omitempty"`
	Uint32        []uint32               `protobuf:"varint,3,rep,packed,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64        []uint64               `protobuf:"varint,4,rep,packed,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32        []int32                `protobuf:"zigzag32,5,rep,packed,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64        []int64                `protobuf:"zigzag64,6,rep,packed,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32       []uint32               `protobuf:"fixed32,7,rep,packed,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64       []uint64               `protobuf:"fixed64,8,rep,packed,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32      []int32                `protobuf:"fixed32,9,rep,packed,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64      []int64                `protobuf:"fixed64,10,rep,packed,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Float         []float32              `protobuf:"fixed32,11,rep,packed,name=float,proto3" json:"float,omitempty"`
	Double        []float64              `protobuf:"fixed64,12,rep,packed,name=double,proto3" json:"double,omitempty"`
	Bool          []bool                 `protobuf:"varint,13,rep,packed,name=bool,proto3" json:"bool,omitempty"`
	String_       []string               `protobuf:"bytes,14,rep,name=string,proto3" json:"string,omitempty"`
	Bytes         [][]byte               `protobuf:"bytes,15,rep,name=bytes,proto3" json:"bytes,omitempty"`
	Message       []*Message             `protobuf:"bytes,16,rep,name=message,proto3" json:"message,omitempty"`
	Language      []Language             `protobuf:"varint,17,rep,packed,name=language,proto3,enum=types.Language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedTypes) Reset() {
	*x = RepeatedTypes{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedTypes) ProtoMessage() {}

func (x *RepeatedTypes) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedTypes.ProtoReflect.Descriptor instead.
func (*RepeatedTypes) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *RepeatedTypes) GetInt32() []int32 {
	if x != nil {
		return x.Int32
	}
	return nil
}

func (x *RepeatedTypes) GetInt64() []int64 {
	if x != nil {
		return x.Int64
	}
	return nil
}

func (x *RepeatedTypes) GetUint32() []uint32 {
	if x != nil {
		return x.Uint32
	}
	return nil
}

func (x *RepeatedTypes) GetUint64() []uint64 {
	if x != nil {
		return x.Uint64
	}
	return nil
}

func (x *RepeatedTypes) GetSint32() []int32 {
	if x != nil {
		return x.Sint32
	}
	return nil
}

func (x *RepeatedTypes) GetSint64() []int64 {
	if x != nil {
		return x.Sint64
	}
	return nil
}

func (x *RepeatedTypes) GetFixed32() []uint32 {
	if x != nil {
		return x.Fixed32
	}
	return nil
}

func (x *RepeatedTypes) GetFixed64() []uint64 {
	if x != nil {
		return x.Fixed64
	}
	return nil
}

func (x *RepeatedTypes) GetSfixed32() []int32 {
	if x != nil {
		return x.Sfixed32
	}
	return nil
}

func (x *RepeatedTypes) GetSfixed64() []int64 {
	if x != nil {
		return x.Sfixed64
	}
	return nil
}

func (x *RepeatedTypes) GetFloat() []float32 {
	if x != nil {
		return x.Float
	}
	return nil
}

func (x *RepeatedTypes) GetDouble() []float64 {
	if x != nil {
		return x.Double
	}
	return nil
}

func (x *RepeatedTypes) GetBool() []bool {
	if x != nil {
		return x.Bool
	}
	return nil
}

func (x *RepeatedTypes) GetString_() []string {
	if x != nil {
		return x.String_
	}
	return nil
}

func (x *RepeatedTypes) GetBytes() [][]byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *RepeatedTypes) GetMessage() []*Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RepeatedTypes) GetLanguage() []Language {
	if x != nil {
		return x.Language
	}
	return nil
}

type RepeatedMixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32         int32                  `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Message       []*Message             `protobuf:"bytes,16,rep,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedMixed) Reset() {
	*x = RepeatedMixed{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedMixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedMixed) ProtoMessage() {}

func (x *RepeatedMixed) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedMixed.ProtoReflect.Descriptor instead.
func (*RepeatedMixed) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedMixed) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *RepeatedMixed) GetMessage() []*Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32         int32                  `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64         int64                  `protobuf:"varint,2,opt,name=int64,proto3" json:"int64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *Message) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthday      int64                  `protobuf:"varint,2,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Siblings      int32                  `protobuf:"varint,4,opt,name=siblings,proto3" json:"siblings,omitempty"`
	Spouse        bool                   `protobuf:"varint,5,opt,name=spouse,proto3" json:"spouse,omitempty"`
	Money         float64                `protobuf:"fixed64,6,opt,name=money,proto3" json:"money,omitempty"`
	Primary       Language               `protobuf:"varint,7,opt,name=primary,proto3,enum=types.Language" json:"primary,omitempty"`
	Spoken        []Language             `protobuf:"varint,8,rep,packed,name=spoken,proto3,enum=types.Language" json:"spoken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

func (x *Person) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Person) GetSiblings() int32 {
	if x != nil {
		return x.Siblings
	}
	return 0
}

func (x *Person) GetSpouse() bool {
	if x != nil {
		return x.Spouse
	}
	return false
}

func (x *Person) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *Person) GetPrimary() Language {
	if x != nil {
		return x.Primary
	}
	return Language_UNKNOWN
}

func (x *Person) GetSpoken() []Language {
	if x != nil {
		return x.Spoken
	}
	return nil
}

type Map struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StringString   map[string]string      `protobuf:"bytes,1,rep,name=string_string,json=stringString,proto3" json:"string_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringInt32    map[string]int32       `protobuf:"bytes,2,rep,name=string_int32,json=stringInt32,proto3" json:"string_int32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringInt64    map[string]int64       `protobuf:"bytes,3,rep,name=string_int64,json=stringInt64,proto3" json:"string_int64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringUint32   map[string]uint32      `protobuf:"bytes,4,rep,name=string_uint32,json=stringUint32,proto3" json:"string_uint32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringUint64   map[string]uint64      `protobuf:"bytes,5,rep,name=string_uint64,json=stringUint64,proto3" json:"string_uint64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringSint32   map[string]int32       `protobuf:"bytes,6,rep,name=string_sint32,json=stringSint32,proto3" json:"string_sint32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"zigzag32,2,opt,name=value"`
	StringSint64   map[string]int64       `protobuf:"bytes,7,rep,name=string_sint64,json=stringSint64,proto3" json:"string_sint64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"zigzag64,2,opt,name=value"`
	StringFixed32  map[string]uint32      `protobuf:"bytes,8,rep,name=string_fixed32,json=stringFixed32,proto3" json:"string_fixed32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	StringFixed64  map[string]uint64      `protobuf:"bytes,9,rep,name=string_fixed64,json=stringFixed64,proto3" json:"string_fixed64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringSfixed32 map[string]int32       `protobuf:"bytes,10,rep,name=string_sfixed32,json=stringSfixed32,proto3" json:"string_sfixed32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	StringSfixed64 map[string]int64       `protobuf:"bytes,11,rep,name=string_sfixed64,json=stringSfixed64,proto3" json:"string_sfixed64,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringFloat    map[string]float32     `protobuf:"bytes,12,rep,name=string_float,json=stringFloat,proto3" json:"string_float,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	StringDouble   map[string]float64     `protobuf:"bytes,13,rep,name=string_double,json=stringDouble,proto3" json:"string_double,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringBool     map[string]bool        `protobuf:"bytes,14,rep,name=string_bool,json=stringBool,proto3" json:"string_bool,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringBytes    map[string][]byte      `protobuf:"bytes,16,rep,name=string_bytes,json=stringBytes,proto3" json:"string_bytes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Int32String    map[int32]string       `protobuf:"bytes,17,rep,name=int32_string,json=int32String,proto3" json:"int32_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Int64String    map[int64]string       `protobuf:"bytes,18,rep,name=int64_string,json=int64String,proto3" json:"int64_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uint32String   map[uint32]string      `protobuf:"bytes,19,rep,name=uint32_string,json=uint32String,proto3" json:"uint32_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uint64String   map[uint64]string      `protobuf:"bytes,20,rep,name=uint64_string,json=uint64String,proto3" json:"uint64_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sint32String   map[int32]string       `protobuf:"bytes,21,rep,name=sint32_string,json=sint32String,proto3" json:"sint32_string,omitempty" protobuf_key:"zigzag32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sint64String   map[int64]string       `protobuf:"bytes,22,rep,name=sint64_string,json=sint64String,proto3" json:"sint64_string,omitempty" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fixed32String  map[uint32]string      `protobuf:"bytes,23,rep,name=fixed32_string,json=fixed32String,proto3" json:"fixed32_string,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fixed64String  map[uint64]string      `protobuf:"bytes,24,rep,name=fixed64_string,json=fixed64String,proto3" json:"fixed64_string,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sfixed32String map[int32]string       `protobuf:"bytes,25,rep,name=sfixed32_string,json=sfixed32String,proto3" json:"sfixed32_string,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sfixed64String map[int64]string       `protobuf:"bytes,26,rep,name=sfixed64_string,json=sfixed64String,proto3" json:"sfixed64_string,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BoolString     map[bool]string        `protobuf:"bytes,27,rep,name=bool_string,json=boolString,proto3" json:"bool_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Map) Reset() {
	*x = Map{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *Map) GetStringString() map[string]string {
	if x != nil {
		return x.StringString
	}
	return nil
}

func (x *Map) GetStringInt32() map[string]int32 {
	if x != nil {
		return x.StringInt32
	}
	return nil
}

func (x *Map) GetStringInt64() map[string]int64 {
	if x != nil {
		return x.StringInt64
	}
	return nil
}

func (x *Map) GetStringUint32() map[string]uint32 {
	if x != nil {
		return x.StringUint32
	}
	return nil
}

func (x *Map) GetStringUint64() map[string]uint64 {
	if x != nil {
		return x.StringUint64
	}
	return nil
}

func (x *Map) GetStringSint32() map[string]int32 {
	if x != nil {
		return x.StringSint32
	}
	return nil
}

func (x *Map) GetStringSint64() map[string]int64 {
	if x != nil {
		return x.StringSint64
	}
	return nil
}

func (x *Map) GetStringFixed32() map[string]uint32 {
	if x != nil {
		return x.StringFixed32
	}
	return nil
}

func (x *Map) GetStringFixed64() map[string]uint64 {
	if x != nil {
		return x.StringFixed64
	}
	return nil
}

func (x *Map) GetStringSfixed32() map[string]int32 {
	if x != nil {
		return x.StringSfixed32
	}
	return nil
}

func (x *Map) GetStringSfixed64() map[string]int64 {
	if x != nil {
		return x.StringSfixed64
	}
	return nil
}

func (x *Map) GetStringFloat() map[string]float32 {
	if x != nil {
		return x.StringFloat
	}
	return nil
}

func (x *Map) GetStringDouble() map[string]float64 {
	if x != nil {
		return x.StringDouble
	}
	return nil
}

func (x *Map) GetStringBool() map[string]bool {
	if x != nil {
		return x.StringBool
	}
	return nil
}

func (x *Map) GetStringBytes() map[string][]byte {
	if x != nil {
		return x.StringBytes
	}
	return nil
}

func (x *Map) GetInt32String() map[int32]string {
	if x != nil {
		return x.Int32String
	}
	return nil
}

func (x *Map) GetInt64String() map[int64]string {
	if x != nil {
		return x.Int64String
	}
	return nil
}

func (x *Map) GetUint32String() map[uint32]string {
	if x != nil {
		return x.Uint32String
	}
	return nil
}

func (x *Map) GetUint64String() map[uint64]string {
	if x != nil {
		return x.Uint64String
	}
	return nil
}

func (x *Map) GetSint32String() map[int32]string {
	if x != nil {
		return x.Sint32String
	}
	return nil
}

func (x *Map) GetSint64String() map[int64]string {
	if x != nil {
		return x.Sint64String
	}
	return nil
}

func (x *Map) GetFixed32String() map[uint32]string {
	if x != nil {
		return x.Fixed32String
	}
	return nil
}

func (x *Map) GetFixed64String() map[uint64]string {
	if x != nil {
		return x.Fixed64String
	}
	return nil
}

func (x *Map) GetSfixed32String() map[int32]string {
	if x != nil {
		return x.Sfixed32String
	}
	return nil
}

func (x *Map) GetSfixed64String() map[int64]string {
	if x != nil {
		return x.Sfixed64String
	}
	return nil
}

func (x *Map) GetBoolString() map[bool]string {
	if x != nil {
		return x.BoolString
	}
	return nil
}

type OptionalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32         int32                  `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalMessage) Reset() {
	*x = OptionalMessage{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalMessage) ProtoMessage() {}

func (x *OptionalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalMessage.ProtoReflect.Descriptor instead.
func (*OptionalMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *OptionalMessage) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

type CommandMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Class string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*CommandMessage_Name
	//	*CommandMessage_Message
	//	*CommandMessage_Count
	Command       isCommandMessage_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *CommandMessage) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CommandMessage) GetCommand() isCommandMessage_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandMessage) GetName() string {
	if x != nil {
		if x, ok := x.Command.(*CommandMessage_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *CommandMessage) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Command.(*CommandMessage_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *CommandMessage) GetCount() int32 {
	if x != nil {
		if x, ok := x.Command.(*CommandMessage_Count); ok {
			return x.Count
		}
	}
	return 0
}

type isCommandMessage_Command interface {
	isCommandMessage_Command()
}

type CommandMessage_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

type CommandMessage_Message struct {
	Message *Message `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type CommandMessage_Count struct {
	Count int32 `protobuf:"varint,4,opt,name=count,proto3,oneof"`
}

func (*CommandMessage_Name) isCommandMessage_Command() {}

func (*CommandMessage_Message) isCommandMessage_Command() {}

func (*CommandMessage_Count) isCommandMessage_Command() {}

type HighFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           int64                  `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	Boundary      int64                  `protobuf:"varint,63,opt,name=boundary,proto3" json:"boundary,omitempty"`
	FirstHigh     int64                  `protobuf:"varint,64,opt,name=first_high,json=firstHigh,proto3" json:"first_high,omitempty"`
	Large         int64                  `protobuf:"varint,100000,opt,name=large,proto3" json:"large,omitempty"`
	Max           int64                  `protobuf:"varint,536870911,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighFields) Reset() {
	*x = HighFields{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighFields) ProtoMessage() {}

func (x *HighFields) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighFields.ProtoReflect.Descriptor instead.
func (*HighFields) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *HighFields) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *HighFields) GetBoundary() int64 {
	if x != nil {
		return x.Boundary
	}
	return 0
}

func (x *HighFields) GetFirstHigh() int64 {
	if x != nil {
		return x.FirstHigh
	}
	return 0
}

func (x *HighFields) GetLarge() int64 {
	if x != nil {
		return x.Large
	}
	return 0
}

func (x *HighFields) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05types\x1a\n" +
	"pico.proto\"\x91\x04\n" +
	"\x05Types\x12\x14\n" +
	"\x05int32\x18\x01 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x02 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06uint32\x18\x03 \x01(\rR\x06uint32\x12\x16\n" +
	"\x06uint64\x18\x04 \x01(\x04R\x06uint64\x12\x16\n" +
	"\x06sint32\x18\x05 \x01(\x11R\x06sint32\x12\x16\n" +
	"\x06sint64\x18\x06 \x01(\x12R\x06sint64\x12\x18\n" +
	"\afixed32\x18\a \x01(\aR\afixed32\x12\x18\n" +
	"\afixed64\x18\b \x01(\x06R\afixed64\x12\x1a\n" +
	"\bsfixed32\x18\t \x01(\x0fR\bsfixed32\x12\x1a\n" +
	"\bsfixed64\x18\n" +
	" \x01(\x10R\bsfixed64\x12\x14\n" +
	"\x05float\x18\v \x01(\x02R\x05float\x12\x16\n" +
	"\x06double\x18\f \x01(\x01R\x06double\x12\x12\n" +
	"\x04bool\x18\r \x01(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\x0e \x01(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\x0f \x01(\fR\x05bytes\x120\n" +
	"\amessage\x18\x10 \x01(\v2\x0e.types.MessageB\x06\xa2\x93\x0e\x02\b\x01R\amessage\x12A\n" +
	"\x10optional_message\x18\x11 \x01(\v2\x16.types.OptionalMessageR\x0foptionalMessage\x12+\n" +
	"\blanguage\x18\x12 \x01(\x0e2\x0f.types.LanguageR\blanguage\"\xce\x03\n" +
	"\rRepeatedTypes\x12\x14\n" +
	"\x05int32\x18\x01 \x03(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x02 \x03(\x03R\x05int64\x12\x16\n" +
	"\x06uint32\x18\x03 \x03(\rR\x06uint32\x12\x16\n" +
	"\x06uint64\x18\x04 \x03(\x04R\x06uint64\x12\x16\n" +
	"\x06sint32\x18\x05 \x03(\x11R\x06sint32\x12\x16\n" +
	"\x06sint64\x18\x06 \x03(\x12R\x06sint64\x12\x18\n" +
	"\afixed32\x18\a \x03(\aR\afixed32\x12\x18\n" +
	"\afixed64\x18\b \x03(\x06R\afixed64\x12\x1a\n" +
	"\bsfixed32\x18\t \x03(\x0fR\bsfixed32\x12\x1a\n" +
	"\bsfixed64\x18\n" +
	" \x03(\x10R\bsfixed64\x12\x14\n" +
	"\x05float\x18\v \x03(\x02R\x05float\x12\x16\n" +
	"\x06double\x18\f \x03(\x01R\x06double\x12\x12\n" +
	"\x04bool\x18\r \x03(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\x0e \x03(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\x0f \x03(\fR\x05bytes\x12(\n" +
	"\amessage\x18\x10 \x03(\v2\x0e.types.MessageR\amessage\x12+\n" +
	"\blanguage\x18\x11 \x03(\x0e2\x0f.types.LanguageR\blanguage\"O\n" +
	"\rRepeatedMixed\x12\x14\n" +
	"\x05int32\x18\x01 \x01(\x05R\x05int32\x12(\n" +
	"\amessage\x18\x10 \x03(\v2\x0e.types.MessageR\amessage\"5\n" +
	"\aMessage\x12\x14\n" +
	"\x05int32\x18\x01 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x02 \x01(\x03R\x05int64\"\xec\x01\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bbirthday\x18\x02 \x01(\x03R\bbirthday\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bsiblings\x18\x04 \x01(\x05R\bsiblings\x12\x16\n" +
	"\x06spouse\x18\x05 \x01(\bR\x06spouse\x12\x14\n" +
	"\x05money\x18\x06 \x01(\x01R\x05money\x12)\n" +
	"\aprimary\x18\a \x01(\x0e2\x0f.types.LanguageR\aprimary\x12'\n" +
	"\x06spoken\x18\b \x03(\x0e2\x0f.types.LanguageR\x06spoken\"\xf5\x1a\n" +
	"\x03Map\x12A\n" +
	"\rstring_string\x18\x01 \x03(\v2\x1c.types.Map.StringStringEntryR\fstringString\x12>\n" +
	"\fstring_int32\x18\x02 \x03(\v2\x1b.types.Map.StringInt32EntryR\vstringInt32\x12>\n" +
	"\fstring_int64\x18\x03 \x03(\v2\x1b.types.Map.StringInt64EntryR\vstringInt64\x12A\n" +
	"\rstring_uint32\x18\x04 \x03(\v2\x1c.types.Map.StringUint32EntryR\fstringUint32\x12A\n" +
	"\rstring_uint64\x18\x05 \x03(\v2\x1c.types.Map.StringUint64EntryR\fstringUint64\x12A\n" +
	"\rstring_sint32\x18\x06 \x03(\v2\x1c.types.Map.StringSint32EntryR\fstringSint32\x12A\n" +
	"\rstring_sint64\x18\a \x03(\v2\x1c.types.Map.StringSint64EntryR\fstringSint64\x12D\n" +
	"\x0estring_fixed32\x18\b \x03(\v2\x1d.types.Map.StringFixed32EntryR\rstringFixed32\x12D\n" +
	"\x0estring_fixed64\x18\t \x03(\v2\x1d.types.Map.StringFixed64EntryR\rstringFixed64\x12G\n" +
	"\x0fstring_sfixed32\x18\n" +
	" \x03(\v2\x1e.types.Map.StringSfixed32EntryR\x0estringSfixed32\x12G\n" +
	"\x0fstring_sfixed64\x18\v \x03(\v2\x1e.types.Map.StringSfixed64EntryR\x0estringSfixed64\x12>\n" +
	"\fstring_float\x18\f \x03(\v2\x1b.types.Map.StringFloatEntryR\vstringFloat\x12A\n" +
	"\rstring_double\x18\r \x03(\v2\x1c.types.Map.StringDoubleEntryR\fstringDouble\x12;\n" +
	"\vstring_bool\x18\x0e \x03(\v2\x1a.types.Map.StringBoolEntryR\n" +
	"stringBool\x12>\n" +
	"\fstring_bytes\x18\x10 \x03(\v2\x1b.types.Map.StringBytesEntryR\vstringBytes\x12>\n" +
	"\fint32_string\x18\x11 \x03(\v2\x1b.types.Map.Int32StringEntryR\vint32String\x12>\n" +
	"\fint64_string\x18\x12 \x03(\v2\x1b.types.Map.Int64StringEntryR\vint64String\x12A\n" +
	"\ruint32_string\x18\x13 \x03(\v2\x1c.types.Map.Uint32StringEntryR\fuint32String\x12A\n" +
	"\ruint64_string\x18\x14 \x03(\v2\x1c.types.Map.Uint64StringEntryR\fuint64String\x12A\n" +
	"\rsint32_string\x18\x15 \x03(\v2\x1c.types.Map.Sint32StringEntryR\fsint32String\x12A\n" +
	"\rsint64_string\x18\x16 \x03(\v2\x1c.types.Map.Sint64StringEntryR\fsint64String\x12D\n" +
	"\x0efixed32_string\x18\x17 \x03(\v2\x1d.types.Map.Fixed32StringEntryR\rfixed32String\x12D\n" +
	"\x0efixed64_string\x18\x18 \x03(\v2\x1d.types.Map.Fixed64StringEntryR\rfixed64String\x12G\n" +
	"\x0fsfixed32_string\x18\x19 \x03(\v2\x1e.types.Map.Sfixed32StringEntryR\x0esfixed32String\x12G\n" +
	"\x0fsfixed64_string\x18\x1a \x03(\v2\x1e.types.Map.Sfixed64StringEntryR\x0esfixed64String\x12;\n" +
	"\vbool_string\x18\x1b \x03(\v2\x1a.types.Map.BoolStringEntryR\n" +
	"boolString\x1a?\n" +
	"\x11StringStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10StringInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a>\n" +
	"\x10StringInt64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a?\n" +
	"\x11StringUint32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a?\n" +
	"\x11StringUint64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a?\n" +
	"\x11StringSint32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x11R\x05value:\x028\x01\x1a?\n" +
	"\x11StringSint64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x12R\x05value:\x028\x01\x1a@\n" +
	"\x12StringFixed32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\aR\x05value:\x028\x01\x1a@\n" +
	"\x12StringFixed64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x06R\x05value:\x028\x01\x1aA\n" +
	"\x13StringSfixed32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x0fR\x05value:\x028\x01\x1aA\n" +
	"\x13StringSfixed64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x10R\x05value:\x028\x01\x1a>\n" +
	"\x10StringFloatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a?\n" +
	"\x11StringDoubleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a=\n" +
	"\x0fStringBoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a>\n" +
	"\x10StringBytesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a>\n" +
	"\x10Int32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10Int64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11Uint32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11Uint64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11Sint32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11Sint64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12Fixed32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\aR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12Fixed64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x06R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13Sfixed32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x0fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13Sfixed64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x10R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fBoolStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x0fOptionalMessage\x12\x14\n" +
	"\x05int32\x18\x01 \x01(\x05R\x05int32\"\x8b\x01\n" +
	"\x0eCommandMessage\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x12*\n" +
	"\amessage\x18\x03 \x01(\v2\x0e.types.MessageH\x00R\amessage\x12\x16\n" +
	"\x05count\x18\x04 \x01(\x05H\x00R\x05countB\t\n" +
	"\acommand\"\x87\x01\n" +
	"\n" +
	"HighFields\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x03R\x03low\x12\x1a\n" +
	"\bboundary\x18? \x01(\x03R\bboundary\x12\x1d\n" +
	"\n" +
	"first_high\x18@ \x01(\x03R\tfirstHigh\x12\x16\n" +
	"\x05large\x18\xa0\x8d\x06 \x01(\x03R\x05large\x12\x14\n" +
	"\x03max\x18\xff\xff\xff\xff\x01 \x01(\x03R\x03max*I\n" +
	"\bLanguage\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aENGLISH\x10\x01\x12\v\n" +
	"\aSPANISH\x10\x03\x12\n" +
	"\n" +
	"\x06FRENCH\x10\x04\x12\n" +
	"\n" +
	"\x06GERMAN\x10\x05b\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_types_proto_goTypes = []any{
	(Language)(0),           // 0: types.Language
	(*Types)(nil),           // 1: types.Types
	(*RepeatedTypes)(nil),   // 2: types.RepeatedTypes
	(*RepeatedMixed)(nil),   // 3: types.RepeatedMixed
	(*Message)(nil),         // 4: types.Message
	(*Person)(nil),          // 5: types.Person
	(*Map)(nil),             // 6: types.Map
	(*OptionalMessage)(nil), // 7: types.OptionalMessage
	(*CommandMessage)(nil),  // 8: types.CommandMessage
	(*HighFields)(nil),      // 9: types.HighFields
	nil,                     // 10: types.Map.StringStringEntry
	nil,                     // 11: types.Map.StringInt32Entry
	nil,                     // 12: types.Map.StringInt64Entry
	nil,                     // 13: types.Map.StringUint32Entry
	nil,                     // 14: types.Map.StringUint64Entry
	nil,                     // 15: types.Map.StringSint32Entry
	nil,                     // 16: types.Map.StringSint64Entry
	nil,                     // 17: types.Map.StringFixed32Entry
	nil,                     // 18: types.Map.StringFixed64Entry
	nil,                     // 19: types.Map.StringSfixed32Entry
	nil,                     // 20: types.Map.StringSfixed64Entry
	nil,                     // 21: types.Map.StringFloatEntry
	nil,                     // 22: types.Map.StringDoubleEntry
	nil,                     // 23: types.Map.StringBoolEntry
	nil,                     // 24: types.Map.StringBytesEntry
	nil,                     // 25: types.Map.Int32StringEntry
	nil,                     // 26: types.Map.Int64StringEntry
	nil,                     // 27: types.Map.Uint32StringEntry
	nil,                     // 28: types.Map.Uint64StringEntry
	nil,                     // 29: types.Map.Sint32StringEntry
	nil,                     // 30: types.Map.Sint64StringEntry
	nil,                     // 31: types.Map.Fixed32StringEntry
	nil,                     // 32: types.Map.Fixed64StringEntry
	nil,                     // 33: types.Map.Sfixed32StringEntry
	nil,                     // 34: types.Map.Sfixed64StringEntry
	nil,                     // 35: types.Map.BoolStringEntry
}
var file_types_proto_depIdxs = []int32{
	4,  // 0: types.Types.message:type_name -> types.Message
	7,  // 1: types.Types.optional_message:type_name -> types.OptionalMessage
	0,  // 2: types.Types.language:type_name -> types.Language
	4,  // 3: types.RepeatedTypes.message:type_name -> types.Message
	0,  // 4: types.RepeatedTypes.language:type_name -> types.Language
	4,  // 5: types.RepeatedMixed.message:type_name -> types.Message
	0,  // 6: types.Person.primary:type_name -> types.Language
	0,  // 7: types.Person.spoken:type_name -> types.Language
	10, // 8: types.Map.string_string:type_name -> types.Map.StringStringEntry
	11, // 9: types.Map.string_int32:type_name -> types.Map.StringInt32Entry
	12, // 10: types.Map.string_int64:type_name -> types.Map.StringInt64Entry
	13, // 11: types.Map.string_uint32:type_name -> types.Map.StringUint32Entry
	14, // 12: types.Map.string_uint64:type_name -> types.Map.StringUint64Entry
	15, // 13: types.Map.string_sint32:type_name -> types.Map.StringSint32Entry
	16, // 14: types.Map.string_sint64:type_name -> types.Map.StringSint64Entry
	17, // 15: types.Map.string_fixed32:type_name -> types.Map.StringFixed32Entry
	18, // 16: types.Map.string_fixed64:type_name -> types.Map.StringFixed64Entry
	19, // 17: types.Map.string_sfixed32:type_name -> types.Map.StringSfixed32Entry
	20, // 18: types.Map.string_sfixed64:type_name -> types.Map.StringSfixed64Entry
	21, // 19: types.Map.string_float:type_name -> types.Map.StringFloatEntry
	22, // 20: types.Map.string_double:type_name -> types.Map.StringDoubleEntry
	23, // 21: types.Map.string_bool:type_name -> types.Map.StringBoolEntry
	24, // 22: types.Map.string_bytes:type_name -> types.Map.StringBytesEntry
	25, // 23: types.Map.int32_string:type_name -> types.Map.Int32StringEntry
	26, // 24: types.Map.int64_string:type_name -> types.Map.Int64StringEntry
	27, // 25: types.Map.uint32_string:type_name -> types.Map.Uint32StringEntry
	28, // 26: types.Map.uint64_string:type_name -> types.Map.Uint64StringEntry
	29, // 27: types.Map.sint32_string:type_name -> types.Map.Sint32StringEntry
	30, // 28: types.Map.sint64_string:type_name -> types.Map.Sint64StringEntry
	31, // 29: types.Map.fixed32_string:type_name -> types.Map.Fixed32StringEntry
	32, // 30: types.Map.fixed64_string:type_name -> types.Map.Fixed64StringEntry
	33, // 31: types.Map.sfixed32_string:type_name -> types.Map.Sfixed32StringEntry
	34, // 32: types.Map.sfixed64_string:type_name -> types.Map.Sfixed64StringEntry
	35, // 33: types.Map.bool_string:type_name -> types.Map.BoolStringEntry
	4,  // 34: types.CommandMessage.message:type_name -> types.Message
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	file_types_proto_msgTypes[7].OneofWrappers = []any{
		(*CommandMessage_Name)(nil),
		(*CommandMessage_Message)(nil),
		(*CommandMessage_Count)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
